apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: dritontest1
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tony@gmail.com
    privateKeySecretRef:
      name: dritonkey
    solvers:
    - http01:
        ingress:
          class: nginx
          serviceType: ClusterIP