apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stagging
  namespace: dritontest
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tony@gmail.com
    privateKeySecretRef:
      name: dritonprivate
    solvers:
    - http01:
        ingress:
          class: nginx